import Phaser from 'phaser';
import { GAME_W, GAME_H, UI_STRIP_H, SCALE } from './config.js';
import { inventory } from './systems/InventorySystem.js';

const VERBS = [
  { id: 'walkTo',  label: 'Walk' },
  { id: 'lookAt',  label: 'Look' },
  { id: 'pickUp',  label: 'Pick Up' },
  { id: 'use',     label: 'Use' },
  { id: 'talkTo',  label: 'Talk' },
];

const C = {
  barBg:     0x12122a,
  barBorder: 0x3a3a7e,
  btnNormal: 0x1e2a5a,
  btnHover:  0x2e4a8a,
  btnActive: 0x4a70cc,
  btnTint:   0xc8d4ff,
  slotBg:    0x0d0d1a,
  slotBorder: 0x3a3a5e,
  slotActive: 0x6a6aee,
  statusTint: 0x9999cc,
};

const FONT_KEY = 'pixel';
const FONT_SIZE = 8 * SCALE;
const INV_SLOT  = 18 * SCALE;
const INV_PAD   = 3 * SCALE;
const BTN_W     = 60 * SCALE;
const BTN_H     = 14 * SCALE;
const BTN_PAD   = 2 * SCALE;

export class UIScene extends Phaser.Scene {
  constructor() {
    super({ key: 'UIScene', active: true });
    this._verbBtns    = [];
    this._invSlots    = [];
    this._statusTxt   = null;
    this._toggleBtn   = null;
    this._uiBar       = null;
    this._verbPopup   = null;
    this._settingsPanel = null;
    this._gearBtn     = null;
    this._rulers      = null;
  }

  create() {
    // Transparent camera so GameScene shows through
    this.cameras.main.transparent = true;

    // Ensure registry defaults (GameScene.create runs first, but be safe)
    if (!this.registry.get('uiMode')) this.registry.set('uiMode', 'verbBar');
    if (!this.registry.get('activeVerb')) this.registry.set('activeVerb', 'lookAt');

    this.inventory = inventory;

    // Wait for bitmap font to be generated by GameScene before building UI
    // Initialize settings defaults
    if (this.registry.get('arrowKeys') === undefined) {
      this.registry.set('arrowKeys', true);
    }
    if (this.registry.get('showHotspots') === undefined) {
      this.registry.set('showHotspots', false);
    }
    if (this.registry.get('showRulers') === undefined) {
      this.registry.set('showRulers', false);
    }

    const initUI = () => {
      this._createToggle();
      this._createGearBtn();
      this._buildModeUI();
      this._setupListeners();
      if (this.registry.get('showRulers')) this._createRulers();
    };

    if (this.cache.bitmapFont.has(FONT_KEY)) {
      initUI();
    } else {
      this.cache.bitmapFont.events.once('add', initUI);
    }
  }

  _setupListeners() {

    // Registry watchers
    this.registry.events.on('changedata-uiMode', () => {
      this._clearModeUI();
      this._buildModeUI();
    });

    this.registry.events.on('changedata-hoveredObject', (_p, val) => {
      this._updateStatus(val);
    });

    this.registry.events.on('changedata-statusText', (_p, val) => {
      if (this._statusTxt) this._statusTxt.setText(val || '');
    });

    this.registry.events.on('changedata-currentRoom', () => {
      this._hideVerbPopup();
    });

    this.registry.events.on('changedata-showRulers', (_p, val) => {
      if (val) this._createRulers();
      else this._destroyRulers();
    });

    // Inventory changes
    if (this.inventory) {
      this.inventory.onChange(() => this._rebuildInventory());
    }

    // Verb popup from GameScene
    const gs = this.scene.get('GameScene');
    gs.events.on('showVerbPopup', (data) => this._showVerbPopup(data));

    // Click outside popup dismisses it
    this.input.on('pointerdown', (pointer) => {
      if (this._verbPopup) {
        const b = this._verbPopup._bounds;
        if (b && !b.contains(pointer.x, pointer.y)) {
          this._hideVerbPopup();
        }
      }
    });
  }

  // ─── Toggle button ───────────────────────────────────────────────────────────

  _createToggle() {
    const tx = GAME_W - 6 * SCALE;
    const ty = GAME_H - 6 * SCALE;

    this._toggleBtn = this.add.text(tx, ty, '=', {
      fontFamily: '"Press Start 2P", monospace',
      fontSize: `${8 * SCALE}px`,
      color: '#ffffff',
      backgroundColor: '#333355',
      padding: { x: 5 * SCALE, y: 3 * SCALE },
    })
      .setOrigin(1, 1)
      .setDepth(1100)
      .setInteractive({ useHandCursor: true });

    this._toggleBtn.on('pointerdown', () => {
      const cur = this.registry.get('uiMode') || 'verbBar';
      this.registry.set('uiMode', cur === 'verbBar' ? 'popup' : 'verbBar');
    });
    this._toggleBtn.on('pointerover', () => this._toggleBtn.setAlpha(0.75));
    this._toggleBtn.on('pointerout',  () => this._toggleBtn.setAlpha(1));
  }

  // ─── Mode UI ─────────────────────────────────────────────────────────────────

  _buildModeUI() {
    const mode = this.registry.get('uiMode') || 'verbBar';
    if (mode === 'verbBar') this._buildVerbBar();
  }

  _clearModeUI() {
    this._uiBar?.destroy();      this._uiBar = null;
    this._statusTxt?.destroy();  this._statusTxt = null;
    this._verbBtns.forEach(b => { b.bg?.destroy(); b.txt?.destroy(); b.zone?.destroy(); });
    this._verbBtns = [];
    this._clearInvSlots();
  }

  // ─── Verb bar ────────────────────────────────────────────────────────────────

  _buildVerbBar() {
    const barY = GAME_H - UI_STRIP_H;

    // Bar background
    this._uiBar = this.add.graphics().setDepth(1000);
    this._uiBar.fillStyle(C.barBg, 1);
    this._uiBar.fillRect(0, barY, GAME_W, UI_STRIP_H);
    this._uiBar.lineStyle(1, C.barBorder, 1);
    this._uiBar.lineBetween(0, barY, GAME_W, barY);

    // Status line
    this._statusTxt = this.add.bitmapText(4 * SCALE, barY + 2 * SCALE, FONT_KEY, '', FONT_SIZE)
      .setTint(C.statusTint)
      .setDepth(1001);

    // Verb buttons — single row of 5
    const verbBaseX = 3 * SCALE;
    const verbBaseY = barY + 12 * SCALE;

    VERBS.forEach((verb, i) => {
      const bx = verbBaseX + i * (BTN_W + BTN_PAD);
      const by = verbBaseY;
      this._makeVerbButton(verb, bx, by);
    });

    // Inventory slots (below verbs)
    this._buildInvSlots(barY);

    this._highlightActiveVerb();
  }

  _makeVerbButton(verb, bx, by) {
    const bg = this.add.graphics().setDepth(1001);
    const txt = this.add.bitmapText(
      bx + BTN_W / 2, by + BTN_H / 2 - FONT_SIZE / 2,
      FONT_KEY, verb.label, FONT_SIZE
    ).setTint(C.btnTint).setDepth(1002);

    // Center the text horizontally
    txt.setX(bx + (BTN_W - txt.width) / 2);

    const zone = this.add.zone(bx, by, BTN_W, BTN_H)
      .setOrigin(0, 0)
      .setInteractive({ useHandCursor: true })
      .setDepth(1003);

    const draw = (color) => {
      bg.clear();
      bg.fillStyle(color, 1);
      bg.fillRoundedRect(bx, by, BTN_W, BTN_H, 3 * SCALE);
    };

    draw(C.btnNormal);

    zone.on('pointerover', () => draw(C.btnHover));
    zone.on('pointerout',  () => draw(this.registry.get('activeVerb') === verb.id ? C.btnActive : C.btnNormal));
    zone.on('pointerdown', () => {
      this.registry.set('activeVerb', verb.id);
      this._highlightActiveVerb();
    });

    this._verbBtns.push({ verb, bg, txt, zone, bx, by, draw });
  }

  _highlightActiveVerb() {
    const activeId = this.registry.get('activeVerb');
    for (const b of this._verbBtns) {
      b.draw(b.verb.id === activeId ? C.btnActive : C.btnNormal);
    }
  }

  // ─── Inventory slots ─────────────────────────────────────────────────────────

  _buildInvSlots(barY) {
    const startX   = 3 * SCALE;
    const slotY    = barY + 28 * SCALE;
    const items    = this.inventory ? this.inventory.getAll() : [];
    const maxSlots = Math.min(Math.floor((GAME_W - startX - 30 * SCALE) / (INV_SLOT + INV_PAD)), 12);

    for (let i = 0; i < maxSlots; i++) {
      const sx   = startX + i * (INV_SLOT + INV_PAD);
      const item = items[i] || null;

      const bg = this.add.graphics().setDepth(1001);
      bg.fillStyle(C.slotBg, 1);
      bg.fillRoundedRect(sx, slotY, INV_SLOT, INV_SLOT, 3 * SCALE);
      bg.lineStyle(1, item ? C.slotBorder : 0x252540, 1);
      bg.strokeRoundedRect(sx, slotY, INV_SLOT, INV_SLOT, 3 * SCALE);

      let label = null;
      let zone  = null;

      if (item) {
        const shortLabel = item.label.slice(0, 4);
        label = this.add.bitmapText(
          sx + INV_SLOT / 2, slotY + INV_SLOT / 2 - FONT_SIZE / 2,
          FONT_KEY, shortLabel, FONT_SIZE
        ).setTint(0xffffff).setDepth(1002);
        label.setX(sx + (INV_SLOT - label.width) / 2);

        zone = this.add.zone(sx, slotY, INV_SLOT, INV_SLOT)
          .setOrigin(0, 0)
          .setInteractive({ useHandCursor: true })
          .setDepth(1003);

        zone.on('pointerdown', () => {
          if (this.inventory) this.inventory.setActive(item.id);
          this.registry.set('activeVerb', 'use');
          this._highlightActiveVerb();
        });

        zone.on('pointerover', () => {
          bg.clear();
          bg.fillStyle(0x1a1a3a, 1);
          bg.fillRoundedRect(sx, slotY, INV_SLOT, INV_SLOT, 3 * SCALE);
          bg.lineStyle(1, C.slotActive, 1);
          bg.strokeRoundedRect(sx, slotY, INV_SLOT, INV_SLOT, 3 * SCALE);
          this.registry.set('hoveredObject', { label: item.label, verbs: {} });
        });

        zone.on('pointerout', () => {
          bg.clear();
          bg.fillStyle(C.slotBg, 1);
          bg.fillRoundedRect(sx, slotY, INV_SLOT, INV_SLOT, 3 * SCALE);
          bg.lineStyle(1, C.slotBorder, 1);
          bg.strokeRoundedRect(sx, slotY, INV_SLOT, INV_SLOT, 3 * SCALE);
          this.registry.set('hoveredObject', null);
        });
      }

      this._invSlots.push({ bg, label, zone });
    }
  }

  _clearInvSlots() {
    for (const s of this._invSlots) {
      s.bg?.destroy();
      s.label?.destroy();
      s.zone?.destroy();
    }
    this._invSlots = [];
  }

  _rebuildInventory() {
    this._clearInvSlots();
    const mode = this.registry.get('uiMode') || 'verbBar';
    if (mode === 'verbBar') {
      this._buildInvSlots(GAME_H - UI_STRIP_H);
    }
  }

  // ─── Status line ─────────────────────────────────────────────────────────────

  _updateStatus(hoveredObj) {
    if (!this._statusTxt) return;
    if (!hoveredObj) {
      this._statusTxt.setText(this.registry.get('statusText') || '');
      return;
    }
    const verb      = this.registry.get('activeVerb') || 'lookAt';
    const verbLabel = VERBS.find(v => v.id === verb)?.label || verb;
    this._statusTxt.setText(`${verbLabel} - ${hoveredObj.label}`);
  }

  // ─── Verb popup (Mode B) ──────────────────────────────────────────────────────

  _showVerbPopup(data) {
    this._hideVerbPopup();

    const { x, y, verbs } = data;
    const available = VERBS.filter(v => verbs[v.id]);
    if (!available.length) return;

    const btnW   = 56 * SCALE;
    const btnH   = 12 * SCALE;
    const bPad   = 1 * SCALE;
    const hPad   = 3 * SCALE;
    const popW   = btnW + hPad * 2;
    const popH   = available.length * (btnH + bPad) - bPad + hPad * 2;

    const px = Phaser.Math.Clamp(x - popW / 2, 4 * SCALE, GAME_W - popW - 4 * SCALE);
    const py = Phaser.Math.Clamp(y - popH - 12 * SCALE, 4 * SCALE, GAME_H - popH - 4 * SCALE);

    const container = this.add.container(px, py).setDepth(1200);

    const bg = this.add.graphics();
    bg.fillStyle(0x12122a, 0.97);
    bg.fillRoundedRect(0, 0, popW, popH, 4 * SCALE);
    bg.lineStyle(1, 0x6a6aee, 1);
    bg.strokeRoundedRect(0, 0, popW, popH, 4 * SCALE);
    container.add(bg);

    available.forEach((verb, i) => {
      const by = hPad + i * (btnH + bPad);

      const rowBg = this.add.graphics();
      rowBg.fillStyle(0x2a2a5e, 0);
      rowBg.fillRoundedRect(hPad, by, btnW, btnH, 2 * SCALE);
      container.add(rowBg);

      const txt = this.add.bitmapText(0, by + (btnH - FONT_SIZE) / 2, FONT_KEY, verb.label, FONT_SIZE)
        .setTint(0xc8d4ff);
      txt.setX((popW - txt.width) / 2);
      container.add(txt);

      const zone = this.add.zone(hPad, by, btnW, btnH)
        .setOrigin(0, 0)
        .setInteractive({ useHandCursor: true });
      container.add(zone);

      zone.on('pointerover', () => {
        rowBg.clear();
        rowBg.fillStyle(0x4a4aaa, 1);
        rowBg.fillRoundedRect(hPad, by, btnW, btnH, 2 * SCALE);
      });
      zone.on('pointerout', () => {
        rowBg.clear();
        rowBg.fillStyle(0x2a2a5e, 0);
        rowBg.fillRoundedRect(hPad, by, btnW, btnH, 2 * SCALE);
      });
      zone.on('pointerdown', () => {
        this._hideVerbPopup();
        const gs = this.scene.get('GameScene');
        gs.runActions(verbs[verb.id]);
      });
    });

    this._verbPopup = container;
    this._verbPopup._bounds = new Phaser.Geom.Rectangle(px, py, popW, popH);
  }

  _hideVerbPopup() {
    if (this._verbPopup) {
      this._verbPopup.destroy(true);
      this._verbPopup = null;
    }
  }

  // ─── Settings ───────────────────────────────────────────────────────────────

  _createGearBtn() {
    const tx = GAME_W - 6 * SCALE;
    const ty = GAME_H - UI_STRIP_H - 6 * SCALE;

    this._gearBtn = this.add.text(tx, ty, '*', {
      fontFamily: '"Press Start 2P", monospace',
      fontSize: `${8 * SCALE}px`,
      color: '#ffffff',
      backgroundColor: '#333355',
      padding: { x: 4 * SCALE, y: 3 * SCALE },
    })
      .setOrigin(1, 1)
      .setDepth(1100)
      .setInteractive({ useHandCursor: true });

    this._gearBtn.on('pointerdown', () => this._toggleSettings());
    this._gearBtn.on('pointerover', () => this._gearBtn.setAlpha(0.75));
    this._gearBtn.on('pointerout',  () => this._gearBtn.setAlpha(1));
  }

  _toggleSettings() {
    if (this._settingsPanel) {
      this._hideSettings();
    } else {
      this._showSettings();
    }
  }

  _showSettings() {
    this._hideSettings();

    const panelW = 160 * SCALE;
    const panelH = 96 * SCALE;
    const px = Math.floor((GAME_W - panelW) / 2);
    const py = Math.floor((GAME_H - panelH) / 2) - 10 * SCALE;

    const container = this.add.container(px, py).setDepth(1300);

    const bg = this.add.graphics();
    bg.fillStyle(0x12122a, 0.95);
    bg.fillRoundedRect(0, 0, panelW, panelH, 4 * SCALE);
    bg.lineStyle(1, 0x6a6aee, 1);
    bg.strokeRoundedRect(0, 0, panelW, panelH, 4 * SCALE);
    container.add(bg);

    const title = this.add.bitmapText(panelW / 2, 6 * SCALE, FONT_KEY, 'SETTINGS', FONT_SIZE)
      .setTint(0xffffff);
    title.setX((panelW - title.width) / 2);
    container.add(title);

    this._addToggleRow(container, panelW, 'Arrow Keys', 'arrowKeys',    22 * SCALE);
    this._addToggleRow(container, panelW, 'Hotspots',   'showHotspots', 40 * SCALE);
    this._addToggleRow(container, panelW, 'Rulers',     'showRulers',   58 * SCALE);

    const closeBtn = this.add.bitmapText(panelW - 12 * SCALE, 4 * SCALE, FONT_KEY, 'X', FONT_SIZE)
      .setTint(0xff6666)
      .setInteractive({ useHandCursor: true });
    container.add(closeBtn);
    closeBtn.on('pointerdown', () => this._hideSettings());

    this._settingsPanel = container;
  }

  _addToggleRow(container, panelW, label, registryKey, rowY) {
    const labelTxt = this.add.bitmapText(10 * SCALE, rowY + 2 * SCALE, FONT_KEY, label, FONT_SIZE)
      .setTint(0xc8d4ff);
    container.add(labelTxt);

    const toggleW = 28 * SCALE;
    const toggleH = 12 * SCALE;
    const toggleX = panelW - toggleW - 10 * SCALE;
    const toggleY = rowY;

    const toggleBg = this.add.graphics();
    const toggleKnob = this.add.graphics();

    const drawToggle = (on) => {
      toggleBg.clear();
      toggleBg.fillStyle(on ? 0x4a70cc : 0x333355, 1);
      toggleBg.fillRoundedRect(toggleX, toggleY, toggleW, toggleH, 3 * SCALE);
      toggleBg.lineStyle(1, 0x6a6aee, 1);
      toggleBg.strokeRoundedRect(toggleX, toggleY, toggleW, toggleH, 3 * SCALE);

      toggleKnob.clear();
      const knobX = on ? toggleX + toggleW - 12 * SCALE : toggleX + 2 * SCALE;
      toggleKnob.fillStyle(0xffffff, 1);
      toggleKnob.fillRoundedRect(knobX, toggleY + 2 * SCALE, 10 * SCALE, toggleH - 4 * SCALE, 2 * SCALE);
    };

    drawToggle(!!this.registry.get(registryKey));
    container.add(toggleBg);
    container.add(toggleKnob);

    const toggleZone = this.add.zone(toggleX, toggleY, toggleW, toggleH)
      .setOrigin(0, 0)
      .setInteractive({ useHandCursor: true });
    container.add(toggleZone);

    toggleZone.on('pointerdown', () => {
      const cur = !!this.registry.get(registryKey);
      this.registry.set(registryKey, !cur);
      drawToggle(!cur);
    });
  }

  _hideSettings() {
    if (this._settingsPanel) {
      this._settingsPanel.destroy(true);
      this._settingsPanel = null;
    }
  }

  // ─── Rulers ─────────────────────────────────────────────────────────────────

  _createRulers() {
    if (this._rulers) return;

    const bottom    = GAME_H;
    const stripSize = 8 * SCALE;
    const tickStep  = 10;
    const labelStep = 50;
    const baseW     = GAME_W / SCALE;
    const baseH     = GAME_H / SCALE;

    const g = this.add.graphics().setDepth(1050);
    const labels = [];

    g.fillStyle(0x000000, 0.65);
    g.fillRect(0, 0, stripSize, bottom);
    g.fillRect(0, bottom - stripSize, GAME_W, stripSize);

    g.lineStyle(1, 0xffff88, 0.95);

    for (let bx = 0; bx <= baseW; bx += tickStep) {
      const cx = bx * SCALE;
      const major = bx % labelStep === 0;
      const h = major ? stripSize : stripSize * 0.5;
      g.lineBetween(cx, bottom - h, cx, bottom);
    }

    for (let by = 0; by <= baseH; by += tickStep) {
      const cy = by * SCALE;
      const major = by % labelStep === 0;
      const w = major ? stripSize : stripSize * 0.5;
      g.lineBetween(0, cy, w, cy);
    }

    const mkLabel = (x, y, text, ox, oy) => {
      const t = this.add.bitmapText(x, y, FONT_KEY, text, FONT_SIZE)
        .setTint(0xffff88)
        .setDepth(1051)
        .setOrigin(ox, oy);
      labels.push(t);
    };

    for (let bx = labelStep; bx < baseW; bx += labelStep) {
      mkLabel(bx * SCALE, bottom - stripSize - 1, String(bx), 0.5, 1);
    }
    mkLabel(GAME_W - 1, bottom - stripSize - 1, String(baseW), 1, 1);

    for (let by = labelStep; by < baseH; by += labelStep) {
      mkLabel(stripSize + 1, by * SCALE, String(by), 0, 0.5);
    }
    mkLabel(stripSize + 1, bottom - stripSize - 1, String(baseH), 0, 1);

    this._rulers = { g, labels };
  }

  _destroyRulers() {
    if (!this._rulers) return;
    this._rulers.g.destroy();
    this._rulers.labels.forEach(t => t.destroy());
    this._rulers = null;
  }

  // ─── Update ──────────────────────────────────────────────────────────────────

  update() {
    // Keep status refreshed with active verb label if something is hovered
    const hovered = this.registry.get('hoveredObject');
    if (hovered !== undefined) this._updateStatus(hovered);
  }
}
